/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js during setup. It is included here so the
// exported app type-checks before dependencies are installed.
